### ISSUE TITLE
How to automatically discover the index file number of binlog ？

### ISSUE THREAD

**Issue by zhengqiangtan** [allwefantasy/spark-binlog#12]
**Hi,excuse me!**
The indexes and offsets of the sample MySQL in the documentation are hard-coded. How do you track changes to the index file? And when the consumption interval is very big when the program hangs, how to carry on the consumption from the place of failure?

> mysql binglog
![image](https://user-images.githubusercontent.com/12029814/70616920-7f78c400-1c4a-11ea-8f8a-8a67bc21f593.png)

**Comment by allwefantasy** [comment]
Since the spark-binlog is a standard spark datasource, this means it will try to keep the exactly-once delivery promise which including situation happens e.g. application crash/restart. spark-binlog will persist the lasted committed offset(offset=logFileIndex + Position)  in checkpoint directory.  Every time when it starts up again,spark-binlog will get the offset from checkpoint instead of your configuration in code.

**Comment by allwefantasy** [comment]
In another case that everything goes fine, and the binlog event will contain the message of the log file name, so we can keep track of the change of names.

**Comment by zhengqiangtan** [comment]
Thank you for your answer @allwefantasy
